// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace RamjetAnvil.Unity.Utility
{

	public static class PlatformUtil
	{
		public enum OperatingSystem { Windows, MacOsx, Linux, Other }
        public enum Architecture {
            X86,
            X64,
            Universal
        }

        private static readonly IDictionary<RuntimePlatform, OperatingSystem> OperatingSystems = new Dictionary<RuntimePlatform, OperatingSystem> {
			{RuntimePlatform.OSXDashboardPlayer, OperatingSystem.MacOsx},
			{RuntimePlatform.OSXEditor, OperatingSystem.MacOsx},
			{RuntimePlatform.OSXPlayer, OperatingSystem.MacOsx},
			{RuntimePlatform.LinuxPlayer, OperatingSystem.Linux},
            //{RuntimePlatform.LinuxEditor, OperatingSystem.Linux},
			{RuntimePlatform.WindowsEditor, OperatingSystem.Windows},
			{RuntimePlatform.WindowsPlayer, OperatingSystem.Windows},
		};
		public static OperatingSystem CurrentOs() {
			OperatingSystem os;
			if(!OperatingSystems.TryGetValue(Application.platform, out os)) {
				os = OperatingSystem.Other;
			}
			return os;
		}
	}
}

